export const RESOURCE_KEYS = {
  USERS: 'pos_users',
  PRODUCTS: 'pos_products',
  CURRENT_USER: 'pos_current_user',
  CATEGORIES: 'pos_categories',
  UOM: 'pos_uom',
  CONTACTS: 'pos_contacts',
  PAYMENT_METHODS: 'pos_payment_methods',
  WAREHOUSES: 'pos_warehouses',
  SHOPS: 'pos_data_shops',
  SESSIONS: 'pos_data_sessions',
  ORDERS: 'pos_data_orders',
  ORDER_LINES: 'pos_data_order_lines',
  PAYMENTS: 'pos_data_payments',
  STOCK_ADJUSTMENTS: 'pos_data_stock_adjustments',
  PURCHASE_ORDERS: 'pos_data_purchase_orders',
  PURCHASE_ORDER_LINES: 'pos_data_purchase_order_lines',
  PROMOTIONS: 'pos_promotions',
  PRICE_GROUPS: 'pos_price_groups',
  PRICE_GROUP_ITEMS: 'pos_price_group_items',
} as const;
